### ISSUE TITLE
Mine for charity

### ISSUE THREAD

**Issue by prekucki** [Thorg-Dev/Thorg-Desktop#9]
![mine for charity](https://user-images.githubusercontent.com/56750/163384408-6cea4b5f-0991-4d41-9d5a-0dcb530d236d.png)

**Comment by IllusiveS** [comment]
- UI
- add to Provider.Config.Charity (adres portfela i procent kasy)
- public Config? Config get i set charity
- alter GlobalsState in https://github.com/golemfactory/ya-provider/blob/main/src/config/globals.rs
- ya-provider command line for set and get json values
